[workspace]
members = [
    "sw/lib/xilinx",
    "sw/lib/neorv32",
    "sw/app/blinky",
    "sw/app/ethernet_demo",
    # "sw/app/ethernet_demo_client",
    "sw/app/dma_demo",
    "sw/app/tpu_app",
]
resolver = "3"
